# Prototype 3: Email the Report
# Builds on Prototype 1 & 2 - adds email functionality

# Import the construction data
$data = Import-Csv "C:\ReactGitEC2\IS305 Scripting\Z_PowerShell_Scripting\Data\Construction_Data_PM_Forms_All_Projects.csv"

# Count total records
$totalCount = $data.Count

# Filter by Status
$openProjects = $data | Where-Object {$_.Status -eq "Open"}
$closedProjects = $data | Where-Object {$_.Status -eq "Closed"}

# Display basic report
Write-Host "`n============================================"
Write-Host "CONSTRUCTION PROJECT STATUS - BASIC REPORT"
Write-Host "============================================"
Write-Host "`nTotal Projects: $totalCount"
Write-Host "Open Projects: $($openProjects.Count)"
Write-Host "Closed Projects: $($closedProjects.Count)"

# Advanced metrics
Write-Host "`n============================================"
Write-Host "ADVANCED METRICS & ANALYSIS"
Write-Host "============================================"

Write-Host "`nSTATUS BREAKDOWN (All Status Types):"
Write-Host "----------------------------------------"
$statusGroups = $data | Group-Object -Property Status
$statusGroups | Format-Table Name, Count -AutoSize

$totalActions = ($data | Measure-Object -Property "Total Actions" -Sum).Sum
$openActions = ($data | Measure-Object -Property "Open Actions" -Sum).Sum
$overdueCount = ($data | Where-Object {$_.OverDue -eq "TRUE"}).Count
$completedActions = $totalActions - $openActions
$completionRate = ($completedActions / $totalActions) * 100
$roundedRate = [Math]::Round($completionRate, 2)

Write-Host "`nADVANCED METRICS:"
Write-Host "----------------------------------------"
Write-Host "Total Projects: $totalCount"
Write-Host "Total Actions: $totalActions"
Write-Host "Open Actions: $openActions"
Write-Host "Completed Actions: $completedActions"
Write-Host "Overdue Items: $overdueCount"
Write-Host "`nCompletion Rate: $roundedRate%"

$stats = $data | Measure-Object -Property "Total Actions" -Average -Maximum -Minimum
Write-Host "`nSTATISTICAL ANALYSIS (Total Actions):"
Write-Host "----------------------------------------"
Write-Host "Average: $([Math]::Round($stats.Average, 2))"
Write-Host "Maximum: $($stats.Maximum)"
Write-Host "Minimum: $($stats.Minimum)"

# NEW: Build email body with the report
$emailBody = @"
CONSTRUCTION PROJECT STATUS REPORT
Generated: $(Get-Date -Format "MMMM dd, yyyy - hh:mm tt")

============================================
SUMMARY
============================================
Total Projects: $totalCount
Open Projects: $($openProjects.Count)
Closed Projects: $($closedProjects.Count)

============================================
ADVANCED METRICS
============================================
Total Actions: $totalActions
Open Actions: $openActions
Completed Actions: $completedActions
Overdue Items: $overdueCount
Completion Rate: $roundedRate%

============================================
STATISTICAL ANALYSIS
============================================
Average Actions per Project: $([Math]::Round($stats.Average, 2))
Maximum Actions: $($stats.Maximum)
Minimum Actions: $($stats.Minimum)

============================================
Report generated by PowerShell
Student: April SYKES | IS305 Scripting
============================================
"@

# NEW: Send email
Write-Host "`n============================================"
Write-Host "SEND EMAIL REPORT"
Write-Host "============================================"

# Ask user where to send the report
$to = Read-Host "`nEnter email address to send report to"

$from = "constructiona1c5@gmail.com"
$password = ConvertTo-SecureString "mjpydjpqpvfqopbg" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential($from, $password)
$subject = "Construction Project Status Report - $(Get-Date -Format 'MM/dd/yyyy')"

Write-Host "`nSending email..."
Write-Host "From: $from"
Write-Host "To: $to"

try {
    Send-MailMessage `
        -From $from `
        -To $to `
        -Subject $subject `
        -Body $emailBody `
        -SmtpServer "smtp.gmail.com" `
        -Port 587 `
        -UseSsl `
        -Credential $credential
    
    Write-Host "`nEMAIL SENT SUCCESSFULLY!" -ForegroundColor Green
}
catch {
    Write-Host "`nEMAIL FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host "============================================`n"
